import 'package:flutter_riverpod/flutter_riverpod.dart';

class LegalItem {
  final String title;
  final String content;
  bool isExpanded;

  LegalItem({required this.title, required this.content, this.isExpanded = false});
}

class SellerLegalScreenState {
  final List<LegalItem> legalItems;

  SellerLegalScreenState({required this.legalItems});

  SellerLegalScreenState copyWith({List<LegalItem>? legalItems}) {
    return SellerLegalScreenState(
      legalItems: legalItems ?? this.legalItems,
    );
  }
}

class SellerLegalScreenStateNotifier extends StateNotifier<SellerLegalScreenState> {
  SellerLegalScreenStateNotifier() : super(SellerLegalScreenState(legalItems: [
    LegalItem(
      title: "Commission & Fees",
      content: "Botaniq charges a flat 10% commission on every successful order. This fee covers platform maintenance and marketing services. All displayed prices must be inclusive of GST where applicable.",
    ),
    LegalItem(
      title: "Payout Schedule",
      content: "Payments for completed orders are processed weekly. Funds will be transferred to your registered bank account every Monday for all orders delivered in the previous week.",
    ),
    LegalItem(
      title: "Product Listing & Content",
      content: "Sellers are responsible for the accuracy of product details. When uploading 'Reels' or promotional videos, ensure content is organic, original, and adheres to our community guidelines. Misleading content may lead to account suspension.",
    ),
    LegalItem(
      title: "Delivery & Returns",
      content: "Sellers must provide accurate pickup locations. You are responsible for ensuring the product is ready for pickup during the designated window. Return pickups must be accepted at the same registered location.",
    ),
    LegalItem(
      title: "Customer Reviews",
      content: "Reviews are generated by verified customers. Sellers may view and respond to reviews professionally. Manipulation of reviews is strictly prohibited.",
    ),
    LegalItem(
      title: "Contact Support",
      content: "For legal inquiries or technical assistance, contact our dedicated support team at: botaniqofficialstore@gmail.com",
    ),
    LegalItem(
      title: "Privacy & Data",
      content: "We protect your business data and customer information. Sellers are prohibited from using customer contact details for marketing outside the Botaniq platform.",
    ),
  ]));

  void toggleExpansion(int index) {
    var newList = List<LegalItem>.from(state.legalItems);
    newList[index].isExpanded = !newList[index].isExpanded;
    state = state.copyWith(legalItems: newList);
  }
}

final sellerLegalScreenStateProvider =
StateNotifierProvider.autoDispose<SellerLegalScreenStateNotifier, SellerLegalScreenState>((ref) => SellerLegalScreenStateNotifier());